spring.application.name=oraclaservice

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

# ===============================
# Datasource Oracle Autonomous
# ===============================
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
#spring.datasource.url=jdbc:oracle:thin:@${DB_TNS_NAME:bdcloud_high}?TNS_ADMIN=C:/Users/cesar/Downloads/Wallet_BDCLOUD
spring.datasource.url=jdbc:oracle:thin:@${DB_TNS_NAME:bdcloud_high}
spring.datasource.username=${DB_USERNAME:PRUEBA_POC}
spring.datasource.password=${DB_PASSWORD:C@ro2026@@47}
oracle.wallet.path=${ORACLE_WALLET_PATH:}

# ===============================
# HikariCP
# ===============================
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2