spring.application.name=oraclaservice

# ===============================
# Health-Sondas-Readiness-Liveness
# ===============================

# Habilitar los probes nativos de Kubernetes
management.endpoint.health.probes.enabled=true
management.endpoints.web.exposure.include=health

# GRUPO LIVENESS: Si falla, AKS REINICIA el Pod.
# Solo incluimos el estado interno y el indicador de hilos (Zombie detection).
management.endpoint.health.group.liveness.include=livenessState,tomcatThreadPool

# GRUPO READINESS: Si falla, AKS SACA el Pod del Ingress.
management.endpoint.health.group.readiness.include=readinessState
#  ,db,mongo,azureServiceBus

# Mostrar detalles para facilitar el soporte tecnico
management.endpoint.health.show-details=always


# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

# ===============================
# Datasource Oracle Autonomous
# ===============================
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
#spring.datasource.url=jdbc:oracle:thin:@${DB_TNS_NAME:bdcloud_high}?TNS_ADMIN=C:/Users/cesar/Downloads/Wallet_BDCLOUD
spring.datasource.url=jdbc:oracle:thin:@${DB_TNS_NAME:bdcloud_high}
spring.datasource.username=${DB_USERNAME:PRUEBA_POC}
spring.datasource.password=${DB_PASSWORD:C@ro2026@@47}
oracle.wallet.path=${ORACLE_WALLET_PATH:}

# ===============================
# HikariCP
# ===============================
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2